name: Deploy to GKE with OIDC

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-deployer@terraform-467505.iam.gserviceaccount.com"

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials dev.devops-gke-cluster --region=us-central1 --project=terraform-467505

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
